#%RAML 1.0
title: Customers API
version: v1
baseUri: https://localhost:8082/api
protocols: [ HTTP, HTTPS ]
mediaType: application/json
types: !include types/types.raml
description: The customers api allows listing, creation, updating and deletion of customers
documentation:
 - title: Please Read!
   content: |
     Welcome to the Customers API Documentation. 
     The Customers API allows you to list, update, create and delete customers from our test database.
     The repository for the application code and RAML spec can be found here on [GitHub](https://github.com/tmarshll/customers-api-demo)
securitySchemes:
  basic:
    description: |
        This API supports Basic Authentication
    type: Basic Authentication
traits:
  compliant: !include compliant.yml
resourceTypes: !include collections.raml
  
/customers:
  type: collection
  description: Allows for bulk operations on the API.
  get:
    responses:
      200:
        body:
          application/json:
            type: customers
            example: !include examples/customers-GET-response.json
  post:
    body:
      application/json:
        type: customers
        example: !include examples/customers-POST-PUT-request.json
    responses:
      201:
        body:
          application/json:
            example: !include examples/customers-POST-PUT-DELETE-response.json
  put:
    body:
      application/json:
        type: customers
        example: !include examples/customers-POST-PUT-request.json
    responses:
      201:
        body:
          application/json:
            example: !include examples/customers-POST-PUT-DELETE-response.json
  delete:
    body:
      application/json:
        type: ids
        example: !include examples/customers-DELETE-request.json
    responses:
      200:
        body:
          application/json:
            example: !include examples/customers-POST-PUT-DELETE-response.json
  /{id}:
    description: Performs operations on a specific customer, given by their id.
    get:
      description: Returns Customer for a given ID
      responses:
        200:
          body:
            application/json:
              type: customer
              example: !include examples/customer-GET-response.json
    put:
      description: Updates a customer from a given payload.
      body:
          type: customer
          example: !include examples/customer-PUT-request.json
      responses:
        200:
          body:
            application/json:
              example: !include examples/customer-POST-PUT-DELETE-response.json
    delete:
      description: Deletes a customer
      responses:
        200:
          body:
            application/json:
              example: !include examples/customer-POST-PUT-DELETE-response.json